services:
  db:
    image: postgres:15-alpine
    container_name: erp_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwe.123*
      POSTGRES_DB: erp_db
    ports:
      - "5445:5432" # P
    volumes:
      - postgres_data_docker:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: src/ERP.Admin/Dockerfile
    container_name: erp_web_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=erp_db;Username=postgres;Password=Qwe.123*
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data_docker: