services:
  # 1. Database
  db:
    image: postgres:15-alpine
    container_name: erp_db_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5445:5432"
    volumes:
      - postgres_data_full:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. ADMIN PANEL Razor
  admin:
    build:
      context: .
      dockerfile: src/ERP.Admin/Dockerfile
    container_name: erp_admin_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - AiSettings__ApiKey=${AI_API-KEY}
      - EmailSettings__Password=${MAIL_PASSWORD}
    ports:
      - "${PORT_WEB}:${PORT_WEB}"
    depends_on:
      db:
        condition: service_healthy

  # 3. API BACKEND 
  api:
    build:
      context: .
      dockerfile: src/ERP.Api/Dockerfile
    container_name: erp_api_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:${PORT_WEB}
      - ConnectionStrings__DefaultConnection=Host=db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - EmailSettings__Password=TU_CLAVE_GMAIL
      - AllowedHosts=*
    ports:
      - "5000:8080" 
    depends_on:
      db:
        condition: service_healthy

  # 4. CLIENT VUE 
  client:
    build:
      context: src/ERP.Client 
      dockerfile: Dockerfile
    container_name: erp_client_container
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data_full: